[workspace]
members = [
    "js",
    "lib",
    "lib/oxrdf",
    "lib/oxsdatatypes",
    "lib/spargebra",
    "lib/sparesults",
    "lib/sparopt",
    "lib/sparql-smith",
    "oxrocksdb-sys",
    "python",
    "server",
    "testsuite"
]

[profile.release]
lto = true
codegen-units = 1

[profile.release.package.oxigraph_js]
opt-level = "z"
