[package]
name = "oxigraph_server"
version = "0.3.1"
authors = ["Tpt <thomas@pellissier-tanon.fr>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/oxigraph/oxigraph/tree/main/server"
homepage = "https://oxigraph.org/server/"
description = """
Oxigraph SPARQL HTTP server
"""
edition = "2021"

[dependencies]
oxhttp = { version = "0.1", features = ["rayon"] }
clap = { version = "3", features = ["derive"] }
oxigraph = { version = "0.3.1", path = "../lib", features = ["http_client"] }
sparesults = { version = "0.1.0", path = "../lib/sparesults", features = ["rdf-star"] }
rand = "0.8"
url = "2"
oxiri = "0.2"
flate2 = "1"
